[package]
name = "respack-decrypter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
glob = "0.3.1"
image = "0.25.5"
oxipng = "9.1.3"
zune-png = "0.4.10"
